def main():
    # open file name names.txt
    infile = open("names.txt", "r")

    line1 = infile.readline()
    line2 = infile.readline()
    line3 = infile.readline()
    line4 = infile.readline()
    line5 = infile.readline()
    line6 = infile.readline()
    line7 = infile.readline()
    line8 = infile.readline()
    line9 = infile.readline()
    line10 = infile.readline()
    line11 = infile.readline()
    line12 = infile.readline()
    line13 = infile.readline()
    line14 = infile.readline()
    line15 = infile.readline()
    line16 = infile.readline()
    line17 = infile.readline()
    line18 = infile.readline()
    line19 = infile.readline()
    line20 = infile.readline()
    line21 = infile.readline()
    line22 = infile.readline()

    infile.close()

    # printing all the names saved in file
    print(line1)
    print(line2)
    print(line3)
    print(line4)
    print(line5)
    print(line6)
    print(line7)
    print(line8)
    print(line9)
    print(line10)
    print(line11)
    print(line12)
    print(line13)
    print(line14)
    print(line15)
    print(line16)
    print(line17)
    print(line18)
    print(line19)
    print(line20)
    print(line21)
    print(line22)


# run the main file
main()
